apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8ca5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0015-tenant/tkrw-pr712-0075-0015-app/devfile-sample-8ca5@sha256:b4d283b5f4c5c4a9154e0d518b0511b7c1fff8d98876da068263fde9c4512a78
        name: my-nodejs
        resources: {}
status: {}
